#!/bin/bash

FILES="bash_profile bashrc gitconfig"

cd 

echo "=== Removing existing symlinks in ~"
find . -maxdepth 1 -type l -lname 'dotfiles/*' -ls -exec rm {} +

echo -e "\n=== Creating new symlinks in ~"
for i in $FILES; do
  dotfile=".$i"
  if [ -e $dotfile ]; then
    echo "ERROR: '$dotfile' already exists. Remove it manually, then run install again."
  else
    ln -vs dotfiles/$i $dotfile
  fi
done

if [ ! -e ~/.bashrc_local ]; then
  echo -e "\n=== WARNING: '~/.bashrc_local' not found."
  echo "You may want to copy the template file (don't forget customizing it!):"
  echo "Use this command: cp ~/dotfiles/bashrc_local.dist ~/.bashrc_local"
fi

echo -e "\n=== Installation completed! You may want to run 'source ~/.bashrc' now."
