#!/bin/bash

FILES="ackrc bash_profile bashrc gitconfig irbrc tm_properties"

cd

echo "=== Removing existing symlinks in ~"
find . -maxdepth 1 -type l -lname 'dotfiles/*' -ls -exec rm {} +

echo -e "\n=== Creating new symlinks in ~"
for i in $FILES; do
  dotfile=".$i"
  if [ -e $dotfile ]; then
    echo "WARNING: '$dotfile' already exists. Renaming to '$dotfile.dotfiles-orig'."
    mv $dotfile $dotfile.dotfiles-orig
  fi
  ln -vs dotfiles/$i $dotfile
done


if [[ "$1" != "--from-da-tool" ]]; then
  if [[ ! -e ~/.bashrc_local ]]; then
    echo -e "\n=== WARNING: '~/.bashrc_local' not found."
    echo "You may want to copy the template file (don't forget customizing it!):"
    echo "Use this command: cp ~/dotfiles/bashrc_local.dist ~/.bashrc_local"
  fi

  echo -e "\n=== Installation completed! You may want to run 'source ~/.bashrc' now."
fi
